# Ini adalah file konfigurasi Frigate untuk pemula
mqtt:
  enabled: false # Kita tidak butuh MQTT untuk simulasi

detectors:
  cpu:
    type: cpu
    num_threads: 2 # Gunakan 2 core CPU (cukup untuk simulasi)

ffmpeg:
  hwaccel_args: auto # Biarkan Frigate otomatis menyesuaikan hardwaremu

cameras:
  video_simulasi:
    enabled: true
    ffmpeg:
      inputs:
        - path: /media/frigate/test_video.avi # Path video di dalam container media/test_video.avi/
          roles:
            - detect # Frigate akan mendeteksi objek di video
            - record # Frigate akan merekam video
    detect:
      width: 1280 # Lebar video (sesuaikan dengan video kamu)
      height: 720 # Tinggi video (sesuaikan dengan video kamu)
      fps: 5 # Jumlah frame per detik (cukup untuk simulasi)
    # record:
    #   enabled: true
    #   retain:
    #     days: 1 # Simpan rekaman selama 1 hari