# Ini adalah file konfigurasi Frigate untuk pemula
mqtt:
  enabled: false # Kita tidak butuh MQTT untuk simulasi

detectors:
  cpu:
    type: cpu
    num_threads: 4 # Gunakan 2 core CPU (cukup untuk simulasi)

ffmpeg:
  hwaccel_args: auto # Biarkan Frigate otomatis menyesuaikan hardwaremu

cameras:
  video_simulasi_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: /media/frigate/test_video_4.mp4 # Path video di dalam container media\test_video_2.mp4
          input_args: -re -stream_loop -1 -fflags +genpts # Tambahkan ini agar video looping dan real-time
          roles:
            - detect # Frigate akan mendeteksi objek di video
            - record # Frigate akan merekam video
  # video_simulasi_2:
  #   enabled: true
  #   ffmpeg:
  #     inputs:
  #       - path: /media/frigate/test_video_5.mp4 # Path video di dalam container media\test_video_2.mp4
  #         input_args: -re -stream_loop -1 -fflags +genpts # Tambahkan ini agar video looping dan real-time
  #         roles:
  #           - detect # Frigate akan mendeteksi objek di video
  #           - record # Frigate akan merekam video
  # video_simulasi_3:
  #   enabled: true
  #   ffmpeg:
  #     inputs:
  #       - path: /media/frigate/test_video_6.mp4 # Path video di dalam container media\test_video_2.mp4
  #         input_args: -re -stream_loop -1 -fflags +genpts # Tambahkan ini agar video looping dan real-time
  #         roles:
  #           - detect # Frigate akan mendeteksi objek di video
  #           - record # Frigate akan merekam video

    detect:
      enabled: true # Pastikan ini eksplisit
      width: 1280 # Lebar video (sesuaikan dengan video kamu)
      height: 720 # Tinggi video (sesuaikan dengan video kamu)
      fps: 5 # Jumlah frame per detik (cukup untuk simulasi)

    objects:
      track:
        - person
        - car
    
    snapshots:
      enabled: true # Wajib aktif agar muncul di menu 'Detections'
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    
    record:
      enabled: true
      retain:
        days: 1 # Simpan rekaman selama 1 hari